### ISSUE TITLE
Outstanding validation TODOs

### ISSUE THREAD

**Issue by tjgalvin** [tjgalvin/flint#46]
There are a couple of TODOs remaining in the validation:
- read in the BMAJ / BMIN / BPA from image headers to include in the plotting and tables
- ensure all columns are built into the tables without placeholders

I think item 1 is really part of item 2. Just need a more thorough read over to make sure. 

@AlecThomson might have a couple of others

**Comment by tjgalvin** [comment]
Also need to pass through the solution files / bandpass SBID / holography file

**Comment by AlecThomson** [comment]
Ping @sunmish

**Comment by Sunmish** [comment]
Are we considering V leakage here as well? If so porting the leakage extraction script would be useful.

**Comment by tjgalvin** [comment]
Most of the todos with regards to the PSF and field summary tables should be complete now with the recent merge of #61 

There remains the outstanding task of merging in this stokes V leakage code.

**Comment by tjgalvin** [comment]
I have added a specific item to pull into flint the stokes v leakage and reporting code. Closing this in favor of that.
