### ISSUE TITLE
Allow the minUV to be passed as an option to AOcalibrate.

### ISSUE THREAD

**Issue by AlecThomson** [tjgalvin/flint#50]
Currently it is hard-coded here:
https://github.com/tjgalvin/flint/blob/bad250237a84eeaa8c05d49d4596d90ec20cccc5/flint/calibrate/aocalibrate.py#L508

**Comment by tjgalvin** [comment]
I have a structure to allow this (and some other `calibrator` options) to be supplied under the `calibrator-validation` branch. By default I have set `-minuv 600`.

**Comment by tjgalvin** [comment]
Addressed in #52
