### ISSUE TITLE
Push the AOcalibrate validation plots to Prefect as an artefact for easy viewing from the pipeline server

### ISSUE THREAD

**Issue by AlecThomson** [tjgalvin/flint#51]
Plots are produced in:
https://github.com/tjgalvin/flint/blob/bad250237a84eeaa8c05d49d4596d90ec20cccc5/flint/calibrate/aocalibrate.py

Would be good to create artefacts in:
https://github.com/tjgalvin/flint/blob/bad250237a84eeaa8c05d49d4596d90ec20cccc5/flint/prefect/flows/bandpass_pipeline.py

**Comment by tjgalvin** [comment]
To support this I would think that the `AOSolutions` class should be extended to have an additional attribute: 

```python
plots: Optional[Tuple[Path,...]] = None
```

which would contain the paths to any plots that are generated. Once the calibration has been completed, but before the `task` returns we upload the markdown.

**Comment by tjgalvin** [comment]
I have ended up adding a `FlaggedAOSolutions` class, which is returned from the function responsible for pre-flagged and smoothing the `AOSolutions` bandpass solutions. 

The `AOSolutions` class was not extended to capture any plots produced.
